import type { Metadata } from 'next'

import "@/styles/globals.css"
import Nav from "@/components/special/nav"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Sora } from 'next/font/google'

const sora = Sora(
  { 
    subsets: ['latin'], 
    weight: ['400'],
  }
)

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <main className={sora.className}>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}

export default RootLayout