import type { Metadata } from 'next'
import { useEffect } from 'react'

import "@/styles/globals.css"
import Nav from "@/components/special/nav"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <main>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}

export default RootLayout